package com.jhonfavo.bootcampvaadin.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class TravelDesign extends VerticalLayout {
	protected TextField search;
	protected Button add;
	protected Grid list;
	protected TextField nama;
	protected TextField notlp;
	protected TextField alamat;
	protected TextField notlp1;
	protected Button update;
	protected Button cancel;
	protected Button delete;

	public TravelDesign() {
		Design.read(this);
	}
}
